version: 2

builds:
  - dir: ./cli
    binary: 'dos'
    goos:
      - linux
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s 
      - -w 
      - -X main.version={{.Version}} 
      - -X main.commit={{.Commit}} 
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    overrides:  
      - goos: windows
        ldflags:
          - -s 
          - -w 
          - -X main.version={{.Version}} 
          - -X main.commit={{.Commit}} 
          - -X main.date={{.Date}}
          - "-H=console"  # Force terminal for Windows
