version: 2


builds:
  - main: main.go
    dir: ./cli
    binary: 'DOS-ClI'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s 
      - -w 
      - -X main.version={{.Version}} 
      - -X main.commit={{.Commit}} 
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0


