import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.className}  antialiased w-full h-full flex flex-col items-center justify-center`}
      >
        <div className="w-full h-fit flex flex-col items-center justify-center max-w-[1280px]">
          {children}
        </div>
      </body>
    </html>
  );
}
