name: Release
on:
  push:
    tags: [ "*" ]

jobs:
  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:

    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
        cache: true
    
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
