
name: Release
on:
  push:
    tags: [ "*" ]
permissions:
  contents: write
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.23.4']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      working-directory: ./cli
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Install dependencies
      working-directory: ./cli
      run: go mod download
    
    - name: Run tests
      working-directory: ./cli
      shell: bash
      run: go test -v ./...

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        working-directory: ./cli
        uses: actions/setup-go@v5
        with:
          go-version: stable
      
      - name: Run GoReleaser
        working-directory: ./cli
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
