name: Release
on:
  push:
    tags:
      - '*' 
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
    
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
