name: Run Tests
on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
    paths:
      - 'cli/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'cli/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.23.4']
    runs-on: ${{ matrix.os }}
    steps:

    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version}}
        cache: true
        cache-dependency-path: cli/go.sum  # Add this line

    - name: Install dependencies
      run: go mod download
      working-directory: ./cli

    - name: Run tests
      shell: bash
      run: go test -v ./...
      working-directory: ./cli
