name: Run Tests
on:
  push:
    branches: [ main, master ]
    tags: [ "*" ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.23.4']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      working-directory: ./cli
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Install dependencies
      working-directory: ./cli
      run: go mod download
    
    - name: Run tests
      working-directory: ./cli
      shell: bash
      run: go test -v ./...
